services:
  # ... other services above ...
  bigcapital:
    image: bigcapitalhq/server:latest
    container_name: bigcapital
    ports:
      - "3000:3000"  # Add this line
    environment:
      # New Relic Configuration - DISABLE IT
      NEW_RELIC_ENABLED: false
      
      # MongoDB Configuration (BigCapital expects MONGODB_DATABASE_URL)
      MONGODB_DATABASE_URL: mongodb://admin:admin_password@bigcapital-mongo:27017/bigcapital?authSource=admin
      
      # MySQL Configuration (BigCapital expects these specific variable names)
      DB_HOST: bigcapital-mariadb
      DB_USER: bigcapital
      DB_PASSWORD: bigcapital_secure_password
      DB_ROOT_PASSWORD: root_password  # Add this if needed
      DB_CHARSET: utf8
      
      # System Database
      SYSTEM_DB_NAME: bigcapital_system
      SYSTEM_DB_HOST: bigcapital-mariadb
      SYSTEM_DB_USER: bigcapital
      SYSTEM_DB_PASSWORD: bigcapital_secure_password
      
      # Tenant Database
      TENANT_DB_NAME_PERFIX: bigcapital_tenant_
      TENANT_DB_HOST: bigcapital-mariadb
      TENANT_DB_USER: bigcapital
      TENANT_DB_PASSWORD: bigcapital_secure_password
      
      # Redis Configuration
      REDIS_HOST: bigcapital-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: bigcapital_redis_password
      
      # Application Configuration
      NODE_ENV: production
      PORT: 3000
      BASE_URL: http://localhost:3000
      
      # Security Configuration
      JWT_SECRET: your-very-secure-jwt-secret-change-this
      SESSION_SECRET: your-very-secure-session-secret-change-this
      
      # Optional: Email Configuration
      # MAIL_HOST: smtp.gmail.com
      # MAIL_PORT: 587
      # MAIL_USERNAME: your-email@gmail.com
      # MAIL_PASSWORD: your-app-password
      # MAIL_FROM_ADDRESS: noreply@yourdomain.com
      # MAIL_FROM_NAME: BigCapital