version: '3.8'

networks:
  paperless_network:
    external: true

services:
  mariadb:
    image: mariadb:10.6
    container_name: bigcapital-mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${SYSTEM_DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - paperless_network
    ports:
      - "3307:3306"

  mongo:
    image: mongo:5.0
    container_name: bigcapital-mongo
    restart: unless-stopped
    volumes:
      - mongo:/data/db
    networks:
      - paperless_network
    ports:
      - "27018:27017"

  redis:
    image: redis:7.0
    container_name: bigcapital-redis
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      - paperless_network
    ports:
      - "6380:6379"

  gotenberg:
    image: gotenberg/gotenberg:7
    container_name: bigcapital-gotenberg
    restart: unless-stopped
    networks:
      - paperless_network
    ports:
      - "9000:3000"

  bigcapital:
    image: bigcapitalhq/server:latest
    container_name: bigcapital
    restart: unless-stopped
    depends_on:
      - mariadb
      - mongo
      - redis
    networks:
      - paperless_network
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment: 
    - NEW_RELIC_ENABLED=false

      

volumes:
  mysql:
    name: bigcapital_mysql
    driver: local
  mongo:
    name: bigcapital_mongo
    driver: local
  redis:
    name: bigcapital_redis
    driver: local