services:
  bigcapital-mongo:
    image: mongo:5.0
    container_name: bigcapital-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
      MONGO_INITDB_DATABASE: bigcapital
    volumes:
      - bigcapital_mongo:/data/db
    networks:
      - paperless_network
    ports:
      - "27018:27017"

  bigcapital:
    image: bigcapitalhq/server:latest
    container_name: bigcapital
    restart: unless-stopped
    environment:
      MONGODB_URI: mongodb://admin:admin_password@bigcapital-mongo:27017/bigcapital?authSource=admin
      MONGO_URI: mongodb://admin:admin_password@bigcapital-mongo:27017/bigcapital?authSource=admin
      # other environment variables for bigcapital...
    depends_on:
      - bigcapital-mongo
      - bigcapital-mariadb
      - bigcapital-redis
    networks:
      - paperless_network
    ports:
      - "3000:3000"

volumes:
  bigcapital_mongo:
    driver: local

networks:
  paperless_network:
    external: true
