version: '3.8'

networks:
  bigcapital_network:
    driver: bridge
    # Connect to the main paperless network for integration
  paperless_network:
    external: true

services:
  # BigCapital Main Application
  bigcapital:
    build:
      context: https://github.com/bigcapitalhq/bigcapital.git#main
      dockerfile: packages/server/Dockerfile
    container_name: bigcapital
    restart: unless-stopped
    depends_on:
      - bigcapital-mariadb
      - bigcapital-mongo
      - bigcapital-redis
    ports:
      - "3000:3000"
    networks:
      - bigcapital_network
      - paperless_network
    environment:
      # Application settings
      - NODE_ENV=production
      - APP_URL=http://simple.local:3000
      - APP_NAME=BigCapital
      - JWT_SECRET=change-me-please-jwt-secret-make-it-long-and-random
      
      # Database configuration
      - DB_HOST=bigcapital-mariadb
      - DB_PORT=3306
      - DB_NAME=bigcapital
      - DB_USER=bigcapital
      - DB_PASSWORD=bigcapital_secure_password
      
      # MongoDB configuration
      - MONGODB_URI=mongodb://bigcapital:bigcapital_mongo_password@bigcapital-mongo:27017/bigcapital
      
      # Redis configuration
      - REDIS_HOST=bigcapital-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=bigcapital_redis_password
      
      # Mail configuration (optional)
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=your-email@gmail.com
      - MAIL_PASSWORD=your-app-password
      - MAIL_FROM_ADDRESS=noreply@yourdomain.com
      - MAIL_FROM_NAME=BigCapital
      
      # File storage
      - STORAGE_DRIVER=local
      - STORAGE_LOCAL_PATH=/app/storage
      
      # API settings
      - API_RATE_LIMIT=1000
      - API_RATE_LIMIT_WINDOW=3600
      
      # Security
      - BCRYPT_ROUNDS=12
      - SESSION_SECRET=another-long-random-secret-for-sessions
      
      # New Relic configuration (disabled for self-hosted)
      - NEW_RELIC_ENABLED=false
      - NEW_RELIC_APP_NAME=BigCapital-SelfHosted
      
    volumes:
      - bigcapital_uploads:/app/uploads
      - bigcapital_storage:/app/storage
      - bigcapital_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # MariaDB Database
  bigcapital-mariadb:
    image: docker.io/library/mariadb:10.11
    container_name: bigcapital-mariadb
    restart: unless-stopped
    networks:
      - bigcapital_network
    environment:
      MYSQL_ROOT_PASSWORD: bigcapital_root_password_change_me
      MYSQL_DATABASE: bigcapital
      MYSQL_USER: bigcapital
      MYSQL_PASSWORD: bigcapital_secure_password
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - bigcapital_mariadb:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"  # Use different external port to avoid conflict
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_connections=200
      - --innodb_buffer_pool_size=256M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "bigcapital", "-pbigcapital_secure_password"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MongoDB Database
  bigcapital-mongo:
    image: docker.io/library/mongo:6.0
    container_name: bigcapital-mongo
    restart: unless-stopped
    networks:
      - bigcapital_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: bigcapital
      MONGO_INITDB_ROOT_PASSWORD: bigcapital_mongo_password
      MONGO_INITDB_DATABASE: bigcapital
    volumes:
      - bigcapital_mongo:/data/db
      - bigcapital_mongo_config:/data/configdb
    ports:
      - "27018:27017"  # Use different external port to avoid conflict
    command: ["mongod", "--auth", "--bind_ip_all"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/bigcapital --quiet
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  bigcapital-redis:
    image: docker.io/library/redis:7-alpine
    container_name: bigcapital-redis
    restart: unless-stopped
    networks:
      - bigcapital_network
    volumes:
      - bigcapital_redis:/data
    ports:
      - "6380:6379"  # Use different external port to avoid conflict
    command: redis-server --requirepass bigcapital_redis_password --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  bigcapital_mariadb:
    driver: local
  bigcapital_mongo:
    driver: local
  bigcapital_mongo_config:
    driver: local
  bigcapital_redis:
    driver: local
  bigcapital_uploads:
    driver: local
  bigcapital_storage:
    driver: local
  bigcapital_logs:
    driver: local
