version: '3.8'

services:
  bigcapital-mariadb:
    image: mariadb:10.6
    container_name: bigcapital-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: bigcapital_root_password_change_me
      MYSQL_DATABASE: bigcapital
      MYSQL_USER: bigcapital
      MYSQL_PASSWORD: bigcapital_secure_password
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - bigcapital_mariadb:/var/lib/mysql
    networks:
      - paperless_network
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "bigcapital", "-pbigcapital_secure_password"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  bigcapital-mongo:
    image: mongo:5.0
    container_name: bigcapital-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
      MONGO_INITDB_DATABASE: bigcapital
    volumes:
      - bigcapital_mongo:/data/db
      - bigcapital_mongo_config:/data/configdb
    networks:
      - paperless_network
    ports:
      - "27018:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok", "--quiet"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  bigcapital-redis:
    image: redis:7.0-alpine
    container_name: bigcapital-redis
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "bigcapital_redis_password", "--appendonly", "yes"]
    volumes:
      - bigcapital_redis:/data
    networks:
      - paperless_network
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "bigcapital_redis_password", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  bigcapital:
    image: bigcapitalhq/server:latest
    container_name: bigcapital
    restart: unless-stopped
    environment:
      # Database Configuration
      MONGODB_URI: mongodb://admin:admin_password@bigcapital-mongo:27017/bigcapital?authSource=admin
      MONGO_URI: mongodb://admin:admin_password@bigcapital-mongo:27017/bigcapital?authSource=admin
      
      # MySQL Configuration
      MYSQL_HOST: bigcapital-mariadb
      MYSQL_PORT: 3306
      MYSQL_DATABASE: bigcapital
      MYSQL_USER: bigcapital
      MYSQL_PASSWORD: bigcapital_secure_password
      
      # Redis Configuration
      REDIS_HOST: bigcapital-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: bigcapital_redis_password
      
      # Application Configuration
      NODE_ENV: production
      PORT: 3000
      
      # Security Configuration (customize these!)
      JWT_SECRET: your-very-secure-jwt-secret-change-this
      SESSION_SECRET: your-very-secure-session-secret-change-this
      
      # Optional: Email Configuration
      # MAIL_HOST: smtp.gmail.com
      # MAIL_PORT: 587
      # MAIL_USERNAME: your-email@gmail.com
      # MAIL_PASSWORD: your-app-password
      # MAIL_FROM_ADDRESS: noreply@yourdomain.com
      # MAIL_FROM_NAME: BigCapital
      
      # Optional: File Storage
      # STORAGE_DRIVER: local
      # UPLOAD_PATH: /app/storage/uploads
      
    volumes:
      - bigcapital_uploads:/app/storage/uploads
      - bigcapital_storage:/app/storage
      - bigcapital_logs:/app/logs
    depends_on:
      bigcapital-mariadb:
        condition: service_healthy
      bigcapital-mongo:
        condition: service_healthy
      bigcapital-redis:
        condition: service_healthy
    networks:
      - paperless_network
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  bigcapital_mariadb:
    driver: local
  bigcapital_mongo:
    driver: local
  bigcapital_mongo_config:
    driver: local
  bigcapital_redis:
    driver: local
  bigcapital_uploads:
    driver: local
  bigcapital_storage:
    driver: local
  bigcapital_logs:
    driver: local

networks:
  paperless_network:
    external: true