name: CI Pipeline - Business Plugin Middleware

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

env:
  DOCKER_IMAGE_NAME: business-plugin-middleware
  DOCKER_HUB_REPO: caston81/business-plugin-middleware

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker Image
        run: docker build -t ${{ env.DOCKER_IMAGE_NAME }} -f docker/Dockerfile .
        
      - name: Run Tests in Docker Container
        run: |
          docker run --rm \
            --entrypoint /bin/bash \
            -v ${{ github.workspace }}:/app \
            -w /app \
            ${{ env.DOCKER_IMAGE_NAME }} \
            -c "pip install pytest && pytest tests/ -v"
            
      - name: Test Plugin System
        run: |
          docker run --rm \
            --entrypoint /bin/bash \
            -v ${{ github.workspace }}:/app \
            -w /app \
            ${{ env.DOCKER_IMAGE_NAME }} \
            -c "python -c 'from core.plugin_manager import PluginManager; print(\"Plugin system test passed\")'"
            
      - name: Log in to Docker Hub
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Generate Docker Tags
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        id: meta
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            echo "tags=${{ env.DOCKER_HUB_REPO }}:latest,${{ env.DOCKER_HUB_REPO }}:${{ github.sha }}" >> $GITHUB_OUTPUT
          else
            echo "tags=${{ env.DOCKER_HUB_REPO }}:develop,${{ env.DOCKER_HUB_REPO }}:develop-${{ github.sha }}" >> $GITHUB_OUTPUT
          fi
          
      - name: Tag and Push Docker Image to Docker Hub
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        run: |
          IFS=',' read -ra TAGS <<< "${{ steps.meta.outputs.tags }}"
          for tag in "${TAGS[@]}"; do
            docker tag ${{ env.DOCKER_IMAGE_NAME }} $tag
            docker push $tag
            echo "Pushed: $tag"
          done
          
  plugin-validation:
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Validate Plugin Structure
        run: |
          python -c "
          import os
          import sys
          sys.path.insert(0, '.')
          
          # Check if plugins directory exists
          plugins_dir = 'plugins'
          if os.path.exists(plugins_dir):
              print(f'✓ Plugins directory found: {plugins_dir}')
              
              # List available plugins
              plugins = [d for d in os.listdir(plugins_dir) 
                        if os.path.isdir(os.path.join(plugins_dir, d)) and not d.startswith('.')]
              print(f'✓ Found {len(plugins)} plugin directories: {plugins}')
              
              # Validate each plugin has required files
              for plugin in plugins:
                  plugin_path = os.path.join(plugins_dir, plugin)
                  init_file = os.path.join(plugin_path, '__init__.py')
                  if os.path.exists(init_file):
                      print(f'✓ Plugin {plugin} has __init__.py')
                  else:
                      print(f'✗ Plugin {plugin} missing __init__.py')
                      sys.exit(1)
          else:
              print('ℹ No plugins directory found - this is okay for base installation')
          
          print('✓ Plugin validation completed')
          "
          
  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run Security Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_IMAGE_NAME }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
